# Generated by Django 3.1.2 on 2021-10-07 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0131_update_ts_vector_existing_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='price_create',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
