# Generated by Django 3.1.2 on 2021-10-07 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0132_productvariant_price_create'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='price_create',
        ),
    ]
