# Generated by Django 3.2.8 on 2021-10-26 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_numberpaymentorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='numberpaymentorder',
            name='payment_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Номер платежа'),
        ),
        migrations.AddField(
            model_name='numberpaymentorder',
            name='token',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Токен заказа'),
        ),
    ]
