# Generated by Django 3.2.8 on 2021-10-26 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20211026_0724'),
    ]

    operations = [
        migrations.AddField(
            model_name='numberpaymentorder',
            name='hash_token',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Токен платежа'),
        ),
    ]
