# Generated by Django 3.2.8 on 2021-10-26 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_numberpaymentorder_hash_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='numberpaymentorder',
            name='date_close',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Когда закончить проверку оплаты'),
        ),
    ]
