# Generated by Django 3.2.8 on 2021-10-26 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_numberpaymentorder_date_close'),
    ]

    operations = [
        migrations.AlterField(
            model_name='numberpaymentorder',
            name='date_close',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Когда закончить проверку оплаты'),
        ),
    ]
