# Generated by Django 3.2.8 on 2021-10-27 16:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_numberpaymentorder_date_close'),
    ]

    operations = [
        migrations.AlterField(
            model_name='numberpaymentorder',
            name='date_close',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 10, 27, 16, 53, 20, 113590), null=True, verbose_name='Когда закончить проверку оплаты'),
        ),
    ]
