# Generated by Django 3.2.8 on 2021-10-27 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_numberpaymentorder_date_close'),
    ]

    operations = [
        migrations.AlterField(
            model_name='numberpaymentorder',
            name='date_close',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Когда закончить проверку оплаты'),
        ),
    ]
