# Generated by Django 3.1.2 on 2021-10-06 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0021_auto_20200902_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='periodically_change',
            field=models.BooleanField(default=False, verbose_name='Переодически изменять стоимость'),
        ),
        migrations.AddField(
            model_name='sale',
            name='value_discount',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='sale',
            name='value_frequency',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12),
        ),
    ]
