# Generated by Django 3.2.8 on 2021-10-18 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0047_auto_20200810_1415'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='addresses',
        ),
        migrations.AddField(
            model_name='user',
            name='addresses',
            field=models.TextField(blank=True, null=True),
        ),
    ]
